Fixed libbe.rcs.RCS.installed to handle missing backend binary.
This makes all the failed tests understandable, since they all crash
with strings like:
  AssertionError: Arch RCS not found
Which makes more sense than spitting out the raw CommandError.

It also means that installed_rcs() actually works now ;).