Allow defaults for config.get_val() in case of missing user-config file.
Fixes bug introduced by James Rowe's previous patch:

  $ be list
  Traceback (most recent call last):
    ...
    File ".../libbe/rcs.py", line 34, in _get_matching_rcs
      import arch
    File ".../libbe/arch.py", line 29, in <module>
      client = config.get_val("arch_client")
    File ".../libbe/config.py", line 70, in get_val
    File "/usr/lib/python2.5/codecs.py", line 817, in open
      file = __builtin__.open(filename, mode, buffering)
  IOError: [Errno 2] No such file or directory: '/home/wking/.bugs_everywhere'