Add explicit positional argument specifiers to .format() strings
This fixes issues with Python 2.6 (before the implicit specifiers
introduced by Python 2.7).

  On Fri, Nov 16, 2012 at 09:04:56AM -0600, Daniel Heater wrote:
  > ...
  > Traceback (most recent call last):
  >   File "setup.py", line 22, in <module>
  >     version='{}'.format(version.version()),
  > ValueError: zero length field name in format
  > ...