Don't call cmd.cleanup_now() for recent Bazaar versions.
Bug reported by Michael Chaffin:

> C:\XXX\ZZZ>be init
> Traceback (most recent call last):
>   ...
> AttributeError: 'cmd_root' object has no attribute '_operation'

Due to changes in bzrlib:

revno: 5146 [merge]
committer: Canonical.com Patch Queue Manager <pqm@pqm.ubuntu.com>
branch nick: +trunk
timestamp: Mon 2010-04-12 04:09:46 +0100

So for versions of bzr since then, we don't have to worry about
calling cleanup_now() anymore.