Use _invoke_client (vs. old _u_invoke_client) for Monotone get_workspace_root.
This fixes Chris'

======================================================================
ERROR: Adding entries with the same ID should not increase the number
of children.
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
CommandError: Command failed (1):
      mtn: misuse: workspace required but not found

while executing
      ['mtn', 'automate', 'get_workspace_root']