Add `new` to list of commands that should not default to using the pager.
If the command is run in the pager, access to stdin is tricky, so I
avoid it by default.  I'd just missed the fact that `new -` used
stdin, which caused

  https://bugzilla.redhat.com/show_bug.cgi?id=751473

  $ be new -
  Traceback (most recent call last):
    ...
    File "/usr/lib/python2.7/site-packages/libbe/command/new.py", line 89, in _run
      summary = self.stdin.readline()
    ...
    File "/usr/lib64/python2.7/codecs.py", line 473, in read
      newdata = self.stream.read(size)
  IOError: [Errno 9] Bad file descriptor